name: CD | Dev Docker Image (GitHub Actions Builder)

on:
  push:
    branches-ignore:
      - "refs/tags/*"

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Shallow clone to minimize disk space
          fetch-depth: 1
        
      - name: Enhanced disk space cleanup
        run: |
          echo "Before cleanup:"
          df -h
          
          # Remove large unnecessary directories
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo rm -rf /usr/local/.ghcup
          
          # Clean Docker aggressively
          docker system prune -af
          
          # Clean apt cache
          sudo apt clean
          sudo rm -rf /var/lib/apt/lists/*
          
          # Remove swap file if it exists
          sudo swapoff -a
          sudo rm -f /swapfile
          
          echo "After cleanup:"
          df -h
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Download large files from S3 (if needed)
        run: |
          # Create directories for downloaded files
          mkdir -p models

          # Example: Download specific model files that are too large for Git
          # aws s3 cp s3://${{ secrets.AWS_S3_BUCKET }}/models/your_large_model.safetensors models/
          
          # List what was downloaded
          ls -la models/
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:${{ github.ref == 'refs/heads/main' && 'dev' || github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:buildcache,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1
      
      - name: Image digest
        run: echo "Docker image has been built and pushed to DockerHub"
