name: CI | Test Worker

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  run_tests:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r builder/requirements.txt
          apt-get install ffmpeg libsm6 libxext6 -y || true

      - name: Execute Tests
        run: |
          # Run extension tests
          python src/test_extensions.py
          
          # Then run the API tests
          python src/rp_handler.py --test_input='{"input": "test"}'
          
          # Test ControlNet functionality
          python src/rp_handler.py --test_input='{"input": {"prompt": "Test image", "use_controlnet": true, "control_type": "canny", "control_image": "https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/diffusers/person_image.png"}}'
          
          # Test ReActor face swap functionality
          python src/rp_handler.py --test_input='{"input": {"prompt": "Portrait of a person", "use_reactor": true, "source_face_image": "https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/diffusers/person_image.png"}}'
